### ISSUE TITLE
Looking for libpsvr.zip

### ISSUE THREAD

**Issue by patch6** [alatnet/OpenPSVR#5]
Hello, the file libpsvr.zip fails to download during generate.bat's execution, with the following error:

 Performing download step (download, verify and extract) for 'libpsvr'
  CMake Error at libpsvr-stamp/libpsvr-download-Debug.cmake:49 (message):
    Command failed: 1

If possible, can someone please link to the file?

Is it this? https://github.com/adawarp/libpsvr/archive/master.zip

@SuperEvenSteven @alatnet , please help

**Comment by patch6** [comment]
Okay, I got the libpsvr.zip files from https://github.com/alatnet/libpsvr/archive/master.zip, managed to get the project to build properly without errors, but the build is missing driver.vrresources (of which there is one in \OpenPSVR\deps\openvr\src\openvr\samples\bin\drivers\sample\resources and C:\work\OpenPSVR\driver\resources), register.bat and unregister.bat.

**Comment by alatnet** [comment]
if you wish, there's a separate source branch that doesnt deal with the whole cmake stuff.
the cmake stuff is all SuperEvenSteven's take on a unified build system.
I've basically used a customized VS project file and makefiles to build my stuff which is in the dev branch (except for a makefile).

**Comment by patch6** [comment]
Thank you. Is it this: https://github.com/alatnet/libpsvr ?

**Comment by alatnet** [comment]
yes. that's the libpsvr library that i've made from the forked original.
OpenPSVR also has a dev branch.

**Comment by patch6** [comment]
Ah, thank you.

**Comment by alatnet** [comment]
np
