### ISSUE TITLE
SteamVR 1.6.4 seems to stop the driver from entering VR mode

### ISSUE THREAD

**Issue by patch6** [alatnet/OpenPSVR#7]
Now it just enters desktop mode with viewports on the left and right. I try entering direct mode but the software just doesn't want to switch to that anymore.

I made a complaint with the SteamVR people, but they probably can't do much about it. I guess I should load an older version and play with that, but the old versions seem to need a password to download.

@alatnet, any idea where to go from here?

**Comment by alatnet** [comment]
weird.
maybe it needs a newer version of OpenVR to build off of?
I was using the OpenVR before they did an overhaul of SteamVR.

**Comment by patch6** [comment]
For what it's worth, installing iVRy's free PSVR driver loads SteamVR in direct mode, but uses the OpenPSVR drivers for the head tracking and graphics. You can tell they're running by the 120 hz, as opposed to iVRy's 90 hz.

**Comment by alatnet** [comment]
... err... i dont think it's using OpenPSVR drivers.
OpenPSVR  drivers dont even support direct mode.

**Comment by patch6** [comment]
I don't know what the mode is, but the view is in proper 3d, and when I check the refresh rate in system settings it says 120 hz, and the view is spinning around like it would in OpenPSVR. iVRy alone would have a stable viewpoint and 90 hz.

I realize this isn't a proper solution so I'll probably stop posting about it. Sorry to bother you.

**Comment by alatnet** [comment]
na, it's fine.

**Comment by Shirkie01** [comment]
I built OpenPSVR using the dev branch and openvr 1.5.17, and was able to get it to the spinning.

**Comment by patch6** [comment]
Cool. Your PSVR enters VR mode properly with it? @Shirkie01

**Comment by Shirkie01** [comment]
Yep, I was able to see the SteamVR sample room correctly in VR mode.

**Comment by patch6** [comment]
I'm stumped. I tried downloading that version of openvr and putting it in the proper source directory, building the program and the .dll *still* doesn't put the headset in VR mode.

@alatnet, where in the OpenPSVR code does the driver put the headset in VR mode?

**Comment by alatnet** [comment]
https://github.com/alatnet/OpenPSVR/blob/4c050a7df10542a9369d6a31182a5c94157d0624/src/HMD/OpenPSVR_HMDDeviceDriver.cpp#L202

**Comment by patch6** [comment]
Thanks!

I tried changing the PSVR Control's HID driver to Zadig's libusb-win32 1.2.6.0 driver, and VR mode is working again! So now to figure out the head tracking ...
